// Keep legacy/unapproved motion frozen. The approved base package has its own switch;
// enabling it does not enable older animation sheets or special flourishes for other creatures.
export const CREATURE_SPRITE_ANIMATION_SETTINGS = { enabled: false, approvedBaseEnabled: true };

// The approved level-one package uses the same renderer in combat and the animation lab.
// Keep the global switch off so unrelated creature tiers retain their existing presentation.
const APPROVED_BASE_ANIMATION_UNITS = new Set([
    "Blacksmith",
    "Squire",
    "Peasant",
    "Arbalester",
    "Fairy",
    "Dryad",
    "Wolf",
    "Leprechaun",
    "Scavenger",
    "Orc",
    "Troglodyte",
    "Wandering Mage",
    "Mermaid",
    "Berserker",
    "Centaur",
    "Wolf Rider",
]);

export const usesApprovedBaseAnimations = (unitName: string): boolean =>
    CREATURE_SPRITE_ANIMATION_SETTINGS.approvedBaseEnabled && APPROVED_BASE_ANIMATION_UNITS.has(unitName);

// These shooters release their projectile from an authored frame, in every scene.
export const usesAuthoredRangedRelease = (unitName: string): boolean =>
    ["Orc", "Arbalester", "Dryad", "Centaur"].includes(unitName);

// Approved movement and Squire reactions must be decoded before their first use in combat,
// including while the global creature-animation freeze remains in place.
const UNIT_ATLASES_USED_WHILE_ANIMATIONS_DISABLED = new Set([
    "dryad_lab_walk_atlas",
    "dryad_lab_hit_atlas",
    "dryad_lab_death_atlas",
    "dryad_lab_melee_attack_atlas",
    "dryad_lab_melee_attack_up_atlas",
    "dryad_lab_melee_attack_down_atlas",
    "dryad_lab_attack_atlas",
    "dryad_lab_attack_up_atlas",
    "dryad_lab_attack_down_atlas",
    "fairy_lab_walk_atlas",
    "fairy_lab_idle_atlas",
    "fairy_lab_hit_atlas",
    "fairy_lab_death_atlas",
    "fairy_lab_melee_attack_atlas",
    "fairy_lab_melee_attack_up_atlas",
    "fairy_lab_melee_attack_down_atlas",
    "berserker_walk_atlas",
    "berserker_sword_idle_atlas",
    "berserker_hit_atlas",
    "berserker_death_atlas",
    "berserker_melee_attack_atlas",
    "berserker_melee_attack_up_atlas",
    "berserker_melee_attack_down_atlas",
    "centaur_lab_walk_atlas",
    "centaur_lab_idle_atlas",
    "centaur_lab_hit_atlas",
    "centaur_lab_death_atlas",
    "centaur_lab_melee_attack_atlas",
    "centaur_lab_melee_attack_up_atlas",
    "centaur_lab_melee_attack_down_atlas",
    "centaur_lab_attack_atlas",
    "centaur_lab_attack_up_atlas",
    "centaur_lab_attack_down_atlas",
    "leprechaun_lab_walk_atlas",
    "leprechaun_lab_idle_atlas",
    "leprechaun_lab_hit_atlas",
    "leprechaun_lab_death_atlas",
    "leprechaun_lab_melee_attack_atlas",
    "leprechaun_lab_melee_attack_up_atlas",
    "leprechaun_lab_melee_attack_down_atlas",
    "orc_idle_atlas",
    "orc_walk_atlas",
    "mermaid_walk_atlas_quarter",
    "mermaid_idle_atlas_quarter",
    "mermaid_hit_atlas_quarter",
    "mermaid_death_atlas_quarter",
    "mermaid_melee_attack_atlas_quarter",
    "mermaid_melee_attack_up_atlas_quarter",
    "mermaid_melee_attack_down_atlas_quarter",
    "orc_hit_atlas",
    "orc_death_atlas",
    "orc_attack_atlas",
    "orc_attack_up_atlas",
    "orc_attack_down_atlas",
    "orc_melee_attack_atlas",
    "orc_melee_attack_up_atlas",
    "orc_melee_attack_down_atlas",
    "arbalester_walk_atlas",
    "arbalester_hit_atlas",
    "arbalester_death_atlas",
    "arbalester_attack_atlas",
    "arbalester_attack_up_atlas",
    "arbalester_attack_down_atlas",
    "arbalester_melee_attack_atlas",
    "arbalester_melee_attack_up_atlas",
    "arbalester_melee_attack_down_atlas",
    "blacksmith_walk_atlas",
    "blacksmith_idle_atlas",
    "blacksmith_hit_atlas",
    "blacksmith_death_atlas",
    "blacksmith_melee_attack_atlas",
    "blacksmith_cast_atlas",
    "blacksmith_melee_attack_up_atlas",
    "blacksmith_melee_attack_down_atlas",
    "ash_moth_walk_atlas_quarter",
    "ash_moth_idle_atlas_quarter",
    "ash_moth_cast_atlas_quarter",
    "ash_moth_melee_attack_atlas_quarter",
    "ash_moth_melee_attack_up_atlas_quarter",
    "ash_moth_melee_attack_down_atlas_quarter",
    "ash_moth_hit_atlas_quarter",
    "ash_moth_death_atlas_quarter",
    "peasant_walk_atlas_quarter",
    "peasant_attack_atlas_quarter",
    "peasant_attack_up_atlas_quarter",
    "peasant_attack_down_atlas_quarter",
    "peasant_hit_atlas_quarter",
    "peasant_death_atlas_quarter",
    "wolf_idle_atlas_half",
    "wolf_walk_atlas_half",
    "wolf_hit_atlas_half",
    "wolf_death_atlas_half",
    "wolf_attack_atlas_half",
    "wolf_attack_up_atlas_half",
    "wolf_attack_down_atlas_half",
    "wolf_rider_walk_atlas_quarter",
    "wolf_rider_idle_atlas_quarter",
    "wolf_rider_hit_atlas_quarter",
    "wolf_rider_death_atlas_quarter",
    "wolf_rider_attack_atlas_quarter",
    "wolf_rider_attack_up_atlas_quarter",
    "wolf_rider_attack_down_atlas_quarter",
    "thief_walk_atlas_quarter",
    "scavenger_homm_idle_atlas_quarter",
    "scavenger_combat_hit_atlas_quarter",
    "scavenger_combat_death_atlas_quarter",
    "scavenger_combat_attack_atlas_quarter",
    "scavenger_combat_attack_up_atlas_quarter",
    "scavenger_combat_attack_down_atlas_quarter",
    "troglodyte_walk_atlas_quarter",
    "troglodyte_idle_atlas_quarter",
    "troglodyte_hit_atlas_quarter",
    "troglodyte_death_atlas_quarter",
    "troglodyte_attack_atlas_quarter",
    "troglodyte_attack_up_atlas_quarter",
    "troglodyte_attack_down_atlas_quarter",
    "squire_walk_atlas_quarter",
    "squire_default_atlas_quarter",
    "squire_idle_atlas_quarter",
    "peasant_idle_red_atlas_quarter",
    "squire_hit_atlas_quarter",
    "squire_attack_atlas_quarter",
    "squire_attack_up_atlas_quarter",
    "squire_attack_down_atlas_quarter",
    "squire_death_atlas_quarter",
]);

export const shouldPreloadUnitAnimationAtlas = (key: string, animationsEnabled: boolean): boolean =>
    // The native pager owns a bounded current/next working set, including when all motion is enabled.
    !/^arbalester_idle_page_\d{2}_atlas$/.test(key) &&
    (animationsEnabled || UNIT_ATLASES_USED_WHILE_ANIMATIONS_DISABLED.has(key));
