/**
 * Russian names for what the game labels in English: units, abilities, status effects, spells, artifacts
 * and doctrines. The game and the Russian Knowledge Base still show these in English, so the AI search
 * answers a Russian question with the Russian name and the English one in brackets the first time
 * ("Медуза (Medusa)"): a player reads Russian and can still find the thing in the game.
 *
 * Where the game already has a Russian name it is used (doctrines, Blind Fury, factions); classic Heroes
 * creatures keep their established Russian names. Keys must match the English names in common's data
 * exactly — graph-builder.test.ts fails on any entity that has no Russian name here.
 */
export const RU_NAMES: Readonly<Record<string, string>> = {
    // ---- Units: Chaos
    Orc: "Орк",
    Scavenger: "Падальщик",
    Troglodyte: "Троглодит",
    "Wandering Mage": "Странствующий маг",
    Beholder: "Созерцатель",
    Manticore: "Мантикора",
    Medusa: "Медуза",
    Troll: "Тролль",
    Efreet: "Ифрит",
    "Goblin Knight": "Гоблин-рыцарь",
    Nightmare: "Кошмар",
    Abomination: "Мерзость",
    "Black Dragon": "Чёрный дракон",
    Hydra: "Гидра",
    // ---- Units: Life
    Arbalester: "Арбалетчик",
    Blacksmith: "Кузнец",
    Peasant: "Крестьянин",
    Squire: "Оруженосец",
    "Battle Mage": "Боевой маг",
    Healer: "Целитель",
    Pikeman: "Копейщик",
    Valkyrie: "Валькирия",
    Crusader: "Крестоносец",
    Griffin: "Грифон",
    Monk: "Монах",
    Angel: "Ангел",
    Champion: "Чемпион",
    "Tsar Cannon": "Царь-пушка",
    // ---- Units: Might
    Berserker: "Берсерк",
    Centaur: "Кентавр",
    Mermaid: "Русалка",
    "Wolf Rider": "Наездник на волке",
    Harpy: "Гарпия",
    Hyena: "Гиена",
    Nomad: "Кочевник",
    Wyvern: "Виверна",
    Cyclops: "Циклоп",
    "Ogre Mage": "Огр-маг",
    Zena: "Зена",
    Behemoth: "Бегемот",
    "Frenzied Boar": "Бешеный вепрь",
    Thunderbird: "Птица грома",
    // ---- Units: Nature
    Dryad: "Дриада",
    Fairy: "Фея",
    Leprechaun: "Лепрекон",
    Wolf: "Волк",
    Elf: "Эльф",
    Satyr: "Сатир",
    Trent: "Трент",
    "White Tiger": "Белый тигр",
    "Arachna Spider": "Паук-арахна",
    Mantis: "Богомол",
    Pegasus: "Пегас",
    Unicorn: "Единорог",
    "Arachna Queen": "Королева арахн",
    Gargantuan: "Исполин",
    "Magic Dragon": "Волшебный дракон",

    // ---- Abilities
    "Absolving Arrow": "Очищающая стрела",
    "Absorb Penalties Aura": "Аура поглощения штрафов",
    Aggr: "Агр",
    "AI Driven": "Под управлением ИИ",
    "Angelic Host Blessing": "Благословение ангельского воинства",
    "Arcane Ward Blessing": "Благословение тайного оберега",
    "Area Throw": "Бросок по площади",
    "Arrows Wingshield Blessing": "Благословение крылатого щита от стрел",
    Backstab: "Удар в спину",
    "Basic Tome of Battle Magic": "Базовый том боевой магии",
    "Battle Roar": "Боевой рёв",
    "Bitter Experience": "Горький опыт",
    "Blacksmith Tools": "Кузнечные инструменты",
    "Blind Fury": "Слепая ярость",
    Blindness: "Слепота",
    "Boar Saliva": "Слюна вепря",
    "Book of Chaos": "Книга Хаоса",
    "Book of Healing": "Книга исцеления",
    "Book of Nightmares": "Книга кошмаров",
    "Boost Health": "Усиленное здоровье",
    "Borrowed Grace": "Заёмная благодать",
    Castling: "Рокировка",
    "Chain Lightning": "Цепная молния",
    Chakram: "Чакрам",
    "Crafted Double Punch": "Кованый двойной удар",
    "Crafted Double Shot": "Кованый двойной выстрел",
    "Crafted Frozen Bow": "Кованый ледяной лук",
    "Crafted Frozen Sword": "Кованый ледяной меч",
    Crusade: "Крестовый поход",
    "Deep Wounds Level 1": "Глубокие раны, уровень 1",
    "Deep Wounds Level 2": "Глубокие раны, уровень 2",
    "Deep Wounds Level 3": "Глубокие раны, уровень 3",
    "Dense Flesh": "Плотная плоть",
    "Devour Essence": "Пожирание сущности",
    "Disguise Aura": "Аура маскировки",
    Dodge: "Уклонение",
    "Double Punch": "Двойной удар",
    "Double Shot": "Двойной выстрел",
    "Double Throw": "Двойной бросок",
    "Dulling Defense": "Притупляющая защита",
    "Earth Element": "Стихия земли",
    "Enchanted Skin": "Зачарованная кожа",
    Enchants: "Зачарования",
    "Endless Quiver": "Бесконечный колчан",
    "Fire Breath": "Огненное дыхание",
    "Fire Element": "Стихия огня",
    "Fire Shield": "Огненный щит",
    "Flesh Shield Aura": "Аура щита из плоти",
    "Forest Spellbook": "Лесная книга заклинаний",
    "Guiding Winds Aura": "Аура попутного ветра",
    Hamstring: "Подрезание сухожилий",
    Handyman: "Мастер на все руки",
    "Heavy Armor": "Тяжёлая броня",
    "In Its Own World": "В своём мире",
    Infest: "Заражение",
    "Large Caliber": "Крупный калибр",
    "Leather Armor": "Кожаная броня",
    "Lightning Spin": "Молниеносный вихрь",
    "Limited Supply": "Ограниченный запас",
    "Luck Aura": "Аура удачи",
    "Lucky Strike": "Удачный удар",
    "Made of Fire": "Сотканный из огня",
    Madness: "Безумие",
    "Magic Reflection": "Отражение магии",
    "Magic Shield": "Магический щит",
    Mechanism: "Механизм",
    Miner: "Рудокоп",
    "No Melee": "Без ближнего боя",
    "One in the Field": "И один в поле воин",
    Paralysis: "Паралич",
    "Pegasus Light": "Свет пегаса",
    "Pegasus Might Aura": "Аура мощи пегаса",
    "Penetrating Bite": "Пронзающий укус",
    "Petrifying Gaze": "Окаменяющий взгляд",
    "Piercing Spear": "Пробивающее копьё",
    "Predatory Assimilation": "Хищная ассимиляция",
    "Rallying Volley Aura": "Аура слаженного залпа",
    "Range Null Field Aura": "Аура подавления стрельбы",
    "Rapid Charge": "Стремительный натиск",
    Resurrection: "Воскрешение",
    "Shadow Touch": "Касание тени",
    "Sharpened Weapons Aura": "Аура заточенного оружия",
    "Shatter Armor": "Сокрушение брони",
    "Skewer Strike": "Удар насквозь",
    "Sky Runner": "Небесный бегун",
    "Small Specie": "Мелкий вид",
    Sniper: "Снайпер",
    "Spit Ball": "Плевок",
    Stun: "Оглушение",
    "Sylvan Focus Aura": "Аура лесной сосредоточенности",
    "Terrifying Gaze": "Устрашающий взгляд",
    "Through Shot": "Сквозной выстрел",
    "Tie up the Horses Aura": "Аура «Запрягай коней»",
    "Time Denial": "Отрицание времени",
    "Tome of Elements": "Том стихий",
    "Tome of Might": "Том Силы",
    "Unyielding Power": "Несгибаемая мощь",
    "Venom Cloud Aura": "Аура ядовитого облака",
    "Vine Throw": "Бросок лозы",
    "War Anger Aura": "Аура боевого гнева",
    Wardguard: "Страж-оберег",
    "Warding Mane Blessing": "Благословение оберегающей гривы",
    "Water Element": "Стихия воды",
    "Water Shield": "Водный щит",
    "Web Aura": "Аура паутины",
    "Wild Regeneration": "Дикая регенерация",
    "Wind Element": "Стихия ветра",
    "Wind Flow": "Поток ветра",
    "Wolf Trail Aura": "Аура волчьей тропы",

    // ---- Status effects that are not also ability names
    Freeze: "Заморозка",
    Poison: "Яд",
    "Deep Wounds": "Глубокие раны",
    Break: "Разлом",

    // ---- Spells (those not already listed as abilities)
    Heal: "Лечение",
    "Spiritual Armor": "Духовная броня",
    Blessing: "Благословение",
    Courage: "Храбрость",
    "Helping Hand": "Рука помощи",
    "Mass Heal": "Массовое лечение",
    "Lightning Strike": "Удар молнии",
    "Summon Wolves": "Призыв волков",
    Whirlpool: "Водоворот",
    "Meteor Shower": "Метеоритный дождь",
    "Ring of Fire": "Огненное кольцо",
    Empower: "Усиление чар",
    "Fire Strike": "Огненный удар",
    Fireball: "Огненный шар",
    "Fireforged Sword": "Огнекованый меч",
    Riot: "Буйство",
    "Fire Wall": "Огненная стена",
    "Magic Mirror": "Магическое зеркало",
    Meteorite: "Метеорит",
    Misfortune: "Невезение",
    Smoke: "Дым",
    "Mass Riot": "Массовое буйство",
    "Mass Magic Mirror": "Массовое магическое зеркало",
    Hamstrung: "Подрезанные сухожилия",
    Quagmire: "Трясина",
    "Weakening Beam": "Ослабляющий луч",
    Weakness: "Слабость",
    Curse: "Проклятие",
    Sadness: "Печаль",
    Cowardice: "Трусость",
    Rangebane: "Погибель стрелков",
    "Broken Aegis": "Расколотая эгида",
    Dismorale: "Упадок духа",
    Hidden: "Скрытность",
    Visible: "Видимость",
    Morale: "Мораль",
    "Armor Rune": "Руна брони",
    Craft: "Ковка",
    "Weapon Rune": "Руна оружия",

    // ---- Artifacts
    "Veteran Helm": "Шлем ветерана",
    "Amulet of Resolve": "Амулет решимости",
    "Keen Blade": "Острый клинок",
    "Iron Plate": "Железные латы",
    "Swift Boots": "Быстрые сапоги",
    "Winged Boots": "Крылатые сапоги",
    "Dual Strike Charm": "Талисман двойного удара",
    "Wounding Charm": "Ранящий талисман",
    "Cursed Ward": "Проклятый оберег",
    "Hunter's Longbow": "Длинный лук охотника",
    "Helm of Focus": "Шлем сосредоточенности",
    "Mage's Ring": "Кольцо мага",
    "Warlord's Edge": "Клинок полководца",
    "Titan Plate": "Латы титана",
    "Clover of Fortune": "Клевер удачи",
    "Crown of Command": "Корона командования",
    "Giant's Maul": "Молот великана",
    "Pendant of Vitality": "Кулон жизненной силы",
    "Farsight Quiver": "Колчан дальнозоркости",
    "Berserker's Bond": "Узы берсерка",
    "Tome of Amplification": "Том усиления",
    "Rime Charm": "Талисман инея",
    "Lava Striders": "Лавоходы",
    "Archmage's Ring": "Кольцо архимага",

    // ---- Doctrines (the game's own Russian names)
    Scout: "Разведчик",
    Spymaster: "Мастер шпионажа",
    "Battle Trance": "Боевой транс",
};

/** The Russian name of an English game name, if there is one. */
export const ruName = (name: string): string | undefined => RU_NAMES[name];

/** "Медуза (Medusa)" in Russian text: the Russian name first, the in-game English after it. */
export const ruLabel = (name: string): string => {
    const russian = RU_NAMES[name];
    return russian ? `${russian} (${name})` : name;
};
