import {
    ChaosSynergyNames,
    CREATURES_JSON,
    LifeSynergyNames,
    MightSynergyNames,
    NatureSynergyNames,
    SynergyKeysToPower,
    UNITS_TO_SYNERGY_LEVEL,
} from "@heroesofcrypto/common";
import abilitiesJson from "@heroesofcrypto/common/src/configuration/abilities.json";
import auraEffectsJson from "@heroesofcrypto/common/src/configuration/aura_effects.json";
import effectsJson from "@heroesofcrypto/common/src/configuration/effects.json";
import spellsJson from "@heroesofcrypto/common/src/configuration/spells.json";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

interface CreatureRecord {
    name: string;
    hp: number;
    steps: number;
    speed: number;
    armor: number;
    attack_type: string;
    attack: number;
    attack_damage_min: number;
    attack_damage_max: number;
    attack_range: number;
    range_shots: number;
    shot_distance: number;
    magic_resist: number;
    movement_type: string;
    size: number;
    level: number;
    spells: string[];
    abilities: string[];
}

interface CreatureConfig {
    version: number;
    [faction: string]: number | Record<string, CreatureRecord>;
}

export const RULES_SUMMARY = `# Heroes of Crypto Rules For AI Players

Heroes of Crypto is a readable turn-based tactics game. The model chooses from legal actions; the game engine applies and validates the action.

Core loop:
1. Armies are drafted and placed.
2. Faction synergies and auras are computed.
3. Turn order is determined by speed and morale.
4. The active unit may move, change attack type, attack, cast, wait, defend, or end turn.
5. Damage is resolved by source. Dead units shatter and are removed.
6. Laps progress. If teams stall, the map narrows and late fights can trigger Armageddon.

Draft rules:
- Each team drafts six creature stacks: two level 1, two level 2, one level 3, and one level 4.
- The first action is LOWER choosing an initial pair containing one level 1 and one level 2 creature.
- The opposing team receives an automatic initial pair, then gets an extended pick and extended ban.
- After that, teams alternate pick and ban actions until the required level counts are complete.
- A pick can only choose an available creature at a still-needed level for that team.
- A ban can only remove an available creature when enough creatures remain for both teams to complete their required level counts.
- The legal draft action list is authoritative for pair indexes, creature ids, required levels, and ban legality.

Practical priorities:
- Use damage actions when a clean attack is available.
- Move only through legal paths generated by the engine.
- Ranged units prefer shots while they can avoid melee pressure.
- Cast spells when they create more tempo than a weapon hit: mass buffs, targeted debuffs, heals, resurrection, summons, and movement-control spells are all legal actions when the common validators allow them.
- Prefer lethal hits on high-value units, especially ranged attackers, casters, and fast stacks.
- Check action evaluation metadata for damage ranges, target total HP, target value, retaliation risk, spell target type, spell power type, estimated spell value, and priority score.
- Use evaluate_actions to inspect the built-in tactical ranking, then submit one of the listed action ids.
- Wait is useful only when another allied unit can act before this stack returns.
- Defend is a fallback when position or target quality is poor.

The authoritative rules live in @heroesofcrypto/common. MCP resources are context for planning, not a separate rules implementation.`;

export const STRATEGY_PRIMER = `# Heroes of Crypto Strategy Primer For AI Players

Goal:
- Win by destroying every enemy stack before your own army is destroyed.
- Every decision should improve material advantage, tempo, board control, or future lethal pressure.
- The legal action list is authoritative. Never invent moves, targets, spells, or coordinates.

Draft goals:
- Build a complete army with the required level mix: two level 1, two level 2, one level 3, and one level 4 creature per team.
- The initial pair supplies one level 1 and one level 2 unit. In server-style drafts, one team picks a pair and the other receives an automatic pair.
- In the headless MCP draft, LOWER chooses the initial pair; UPPER receives the automatic pair, then takes an extended pick and extended ban; later actions alternate pick/ban by active team until each army is complete.
- Required level, available creatures, bans, and already-picked creatures are enforced by the legal draft action list.
- Prefer an army with complementary jobs: frontline durability, ranged pressure, magic support, speed/tempo, and at least one high-impact threat.
- In this version, ranged pressure is a core draft axis: try to out-pick the opponent in ranged units, not merely match them.
- Tsar Cannon and Gargantuan are premium ranged threats. Secure one when legal and useful; otherwise ban them or confirm they are already banned/unavailable before allowing the opponent to build around them.
- Ban high-value level 4 units, strong ranged units, strong casters, or creatures that complete an opponent's visible faction plan.
- Do not tunnel on raw stats. A lower-level caster, summon, aura, or fast stack can be worth more than a slow body.

Faction synergy goals:
- Life commonly supports morale, luck, sustain, and supply. Life-heavy armies can snowball through survivability and extra tempo.
- Chaos commonly supports movement and disruptive attack pressure. Chaos-heavy armies can convert reach into first hits.
- Might commonly improves aura reach and stack-powered ability output. Might-heavy armies reward durable clustered fighting.
- Nature commonly rewards board presence and flying/armor themes. Nature-heavy armies can win through summons and unit count.
- Synergy is useful when it improves the current army plan. Do not force a faction if the available unit is tactically weak or redundant.

Turn priorities:
- Lethal attacks on valuable enemies usually beat setup actions.
- Damage high-value threats first: ranged attackers, casters, fast stacks, resurrectors/healers, and level 4 units.
- Prefer actions that remove enemy turns. Killing or crippling a stack is often stronger than spreading damage.
- Use ranged attacks while safe. Reposition ranged units when melee pressure would shut them down.
- Use movement to create a credible attack, block an enemy route, preserve a fragile unit, or keep an aura/synergy formation.
- Avoid attacks with bad retaliation unless the trade kills a valuable target or prevents worse damage.
- Wait only when delaying lets an ally act first or creates a better same-lap attack. Defend only when no useful pressure exists.

Spell priorities:
- Cast mass buffs/debuffs when they affect multiple relevant stacks and the fight is not already decided by a lethal hit.
- Heal or resurrect when it restores a high-value stack or denies enemy tempo.
- Summons are strong when they block paths, add attacks, protect ranged/caster units, or force the opponent to spend actions.
- Single-target damage or control spells are strongest when they kill, disable, or expose a key enemy.
- Do not spend scarce casts on low-impact targets when a weapon hit or position wins more tempo.

Board and lap priorities:
- Watch current lap and narrowing. Late fights punish passive play and exposed edge positions.
- Large units need more space. Do not move them into cells that trap allied melee or block ranged lines unnecessarily.
- Protect fragile casters and ranged units behind durable stacks, but keep them close enough to contribute.
- If ahead, trade safely and deny comeback spells. If behind, seek high-variance plays: lethal focus, summons, control, or risky tempo.

Evaluation metadata:
- priorityScore, targetValue, damage, killsTarget, retaliation, spell estimatedValue, and tacticalTags are model hints generated from game state.
- Use those hints to rank legal actions, but still apply strategic judgment from this primer.`;

export const getUnitRoster = (): Array<{
    faction: string;
    name: string;
    level: number;
    size: number;
    hp: number;
    speed: number;
    steps: number;
    armor: number;
    attackType: string;
    attack: number;
    damage: { min: number; max: number };
    attackRange: number;
    rangeShots: number;
    shotDistance: number;
    magicResist: number;
    movementType: string;
    spells: string[];
    abilities: string[];
}> => {
    const config = CREATURES_JSON as CreatureConfig;
    return Object.entries(config).flatMap(([faction, units]) => {
        if (faction === "version" || typeof units === "number") {
            return [];
        }

        return Object.values(units).map((unit) => ({
            faction,
            name: unit.name,
            level: unit.level,
            size: unit.size,
            hp: unit.hp,
            speed: unit.speed,
            steps: unit.steps,
            armor: unit.armor,
            attackType: unit.attack_type,
            attack: unit.attack,
            damage: {
                min: unit.attack_damage_min,
                max: unit.attack_damage_max,
            },
            attackRange: unit.attack_range,
            rangeShots: unit.range_shots,
            shotDistance: unit.shot_distance,
            magicResist: unit.magic_resist,
            movementType: unit.movement_type,
            spells: unit.spells,
            abilities: unit.abilities,
        }));
    });
};

const jsonContents = (uri: URL, value: unknown) => ({
    contents: [
        {
            uri: uri.href,
            mimeType: "application/json",
            text: JSON.stringify(value, null, 2),
        },
    ],
});

export const getSynergyReference = () => ({
    thresholds: UNITS_TO_SYNERGY_LEVEL,
    powers: SynergyKeysToPower,
    factions: {
        Life: LifeSynergyNames,
        Chaos: ChaosSynergyNames,
        Might: MightSynergyNames,
        Nature: NatureSynergyNames,
    },
    notes: [
        "Synergy levels are unlocked by fielding enough units of a faction.",
        "Life improves supply or morale/luck.",
        "Chaos improves movement or applies Break on attack.",
        "Might increases aura range or stack-powered ability output.",
        "Nature increases board unit count or fly armor.",
    ],
});

export const getAbilityReference = (): typeof abilitiesJson => abilitiesJson;

export const getSpellReference = (): typeof spellsJson => spellsJson;

export const getEffectReference = (): typeof effectsJson => effectsJson;

export const getAuraReference = (): typeof auraEffectsJson => auraEffectsJson;

export const getStrategyPrimer = (): string => STRATEGY_PRIMER;

export const registerGameResources = (server: McpServer): void => {
    server.registerResource(
        "rules-summary",
        "hoc://rules/summary",
        {
            title: "Heroes of Crypto Rules Summary",
            description: "Compact rules summary for model-controlled turns.",
            mimeType: "text/markdown",
        },
        async (uri) => ({
            contents: [{ uri: uri.href, mimeType: "text/markdown", text: RULES_SUMMARY }],
        }),
    );

    server.registerResource(
        "unit-roster",
        "hoc://units",
        {
            title: "Heroes of Crypto Unit Roster",
            description: "Public unit stats, abilities, and spells derived from the common package config.",
            mimeType: "application/json",
        },
        async (uri) => jsonContents(uri, { units: getUnitRoster() }),
    );

    server.registerResource(
        "strategy-primer",
        "hoc://strategy/primer",
        {
            title: "Heroes of Crypto Strategy Primer",
            description: "Goals, draft priorities, synergy guidance, and tactical heuristics for model players.",
            mimeType: "text/markdown",
        },
        async (uri) => ({
            contents: [{ uri: uri.href, mimeType: "text/markdown", text: STRATEGY_PRIMER }],
        }),
    );

    server.registerResource(
        "ability-reference",
        "hoc://abilities",
        {
            title: "Heroes of Crypto Ability Reference",
            description: "Raw public ability data from the common package.",
            mimeType: "application/json",
        },
        async (uri) => jsonContents(uri, abilitiesJson),
    );

    server.registerResource(
        "spell-reference",
        "hoc://spells",
        {
            title: "Heroes of Crypto Spell Reference",
            description: "Raw public spell data from the common package.",
            mimeType: "application/json",
        },
        async (uri) => jsonContents(uri, spellsJson),
    );

    server.registerResource(
        "effect-reference",
        "hoc://effects",
        {
            title: "Heroes of Crypto Effect Reference",
            description: "Raw public effect data from the common package.",
            mimeType: "application/json",
        },
        async (uri) => jsonContents(uri, effectsJson),
    );

    server.registerResource(
        "aura-reference",
        "hoc://auras",
        {
            title: "Heroes of Crypto Aura Reference",
            description: "Raw public aura effect data from the common package.",
            mimeType: "application/json",
        },
        async (uri) => jsonContents(uri, auraEffectsJson),
    );

    server.registerResource(
        "synergy-reference",
        "hoc://synergies",
        {
            title: "Heroes of Crypto Synergy Reference",
            description: "Faction synergy thresholds and powers from the common package.",
            mimeType: "application/json",
        },
        async (uri) => jsonContents(uri, getSynergyReference()),
    );
};
