import {
    ChaosSynergyNames,
    CREATURES_JSON,
    LifeSynergyNames,
    MightSynergyNames,
    NatureSynergyNames,
    SynergyKeysToPower,
    UNITS_TO_SYNERGY_LEVEL,
} from "@heroesofcrypto/common";
import abilitiesJson from "@heroesofcrypto/common/src/configuration/abilities.json";
import auraEffectsJson from "@heroesofcrypto/common/src/configuration/aura_effects.json";
import effectsJson from "@heroesofcrypto/common/src/configuration/effects.json";
import spellsJson from "@heroesofcrypto/common/src/configuration/spells.json";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

interface CreatureRecord {
    name: string;
    hp: number;
    steps: number;
    speed: number;
    armor: number;
    attack_type: string;
    attack: number;
    attack_damage_min: number;
    attack_damage_max: number;
    attack_range: number;
    range_shots: number;
    shot_distance: number;
    magic_resist: number;
    movement_type: string;
    size: number;
    level: number;
    spells: string[];
    abilities: string[];
}

interface CreatureConfig {
    version: number;
    [faction: string]: number | Record<string, CreatureRecord>;
}

export const RULES_SUMMARY = `# Heroes of Crypto Rules For AI Players

Heroes of Crypto is a readable turn-based tactics game. The model chooses from legal actions; the game engine applies and validates the action.

Core loop:
1. Armies are drafted and placed.
2. Faction synergies and auras are computed.
3. Turn order is determined by speed and morale.
4. The active unit may move, change attack type, attack, cast, wait, defend, or end turn.
5. Damage is resolved by source. Dead units shatter and are removed.
6. Laps progress. If teams stall, the map narrows and late fights can trigger Armageddon.

Practical priorities:
- Use damage actions when a clean attack is available.
- Move only through legal paths generated by the engine.
- Ranged units prefer shots while they can avoid melee pressure.
- Cast spells when they create more tempo than a weapon hit: mass buffs, targeted debuffs, heals, resurrection, summons, and movement-control spells are all legal actions when the common validators allow them.
- Prefer lethal hits on high-value units, especially ranged attackers, casters, and fast stacks.
- Check action evaluation metadata for damage ranges, target total HP, target value, retaliation risk, spell target type, spell power type, estimated spell value, and priority score.
- Use evaluate_actions to inspect the built-in tactical ranking, then submit one of the listed action ids.
- Wait is useful only when another allied unit can act before this stack returns.
- Defend is a fallback when position or target quality is poor.

The authoritative rules live in @heroesofcrypto/common. MCP resources are context for planning, not a separate rules implementation.`;

export const getUnitRoster = (): Array<{
    faction: string;
    name: string;
    level: number;
    size: number;
    hp: number;
    speed: number;
    steps: number;
    armor: number;
    attackType: string;
    attack: number;
    damage: { min: number; max: number };
    attackRange: number;
    rangeShots: number;
    shotDistance: number;
    magicResist: number;
    movementType: string;
    spells: string[];
    abilities: string[];
}> => {
    const config = CREATURES_JSON as CreatureConfig;
    return Object.entries(config).flatMap(([faction, units]) => {
        if (faction === "version" || typeof units === "number") {
            return [];
        }

        return Object.values(units).map((unit) => ({
            faction,
            name: unit.name,
            level: unit.level,
            size: unit.size,
            hp: unit.hp,
            speed: unit.speed,
            steps: unit.steps,
            armor: unit.armor,
            attackType: unit.attack_type,
            attack: unit.attack,
            damage: {
                min: unit.attack_damage_min,
                max: unit.attack_damage_max,
            },
            attackRange: unit.attack_range,
            rangeShots: unit.range_shots,
            shotDistance: unit.shot_distance,
            magicResist: unit.magic_resist,
            movementType: unit.movement_type,
            spells: unit.spells,
            abilities: unit.abilities,
        }));
    });
};

const jsonContents = (uri: URL, value: unknown) => ({
    contents: [
        {
            uri: uri.href,
            mimeType: "application/json",
            text: JSON.stringify(value, null, 2),
        },
    ],
});

export const getSynergyReference = () => ({
    thresholds: UNITS_TO_SYNERGY_LEVEL,
    powers: SynergyKeysToPower,
    factions: {
        Life: LifeSynergyNames,
        Chaos: ChaosSynergyNames,
        Might: MightSynergyNames,
        Nature: NatureSynergyNames,
    },
    notes: [
        "Synergy levels are unlocked by fielding enough units of a faction.",
        "Life improves supply or morale/luck.",
        "Chaos improves movement or applies Break on attack.",
        "Might increases aura range or stack-powered ability output.",
        "Nature increases board unit count or fly armor.",
    ],
});

export const registerGameResources = (server: McpServer): void => {
    server.registerResource(
        "rules-summary",
        "hoc://rules/summary",
        {
            title: "Heroes of Crypto Rules Summary",
            description: "Compact rules summary for model-controlled turns.",
            mimeType: "text/markdown",
        },
        async (uri) => ({
            contents: [{ uri: uri.href, mimeType: "text/markdown", text: RULES_SUMMARY }],
        }),
    );

    server.registerResource(
        "unit-roster",
        "hoc://units",
        {
            title: "Heroes of Crypto Unit Roster",
            description: "Public unit stats, abilities, and spells derived from the common package config.",
            mimeType: "application/json",
        },
        async (uri) => jsonContents(uri, { units: getUnitRoster() }),
    );

    server.registerResource(
        "ability-reference",
        "hoc://abilities",
        {
            title: "Heroes of Crypto Ability Reference",
            description: "Raw public ability data from the common package.",
            mimeType: "application/json",
        },
        async (uri) => jsonContents(uri, abilitiesJson),
    );

    server.registerResource(
        "spell-reference",
        "hoc://spells",
        {
            title: "Heroes of Crypto Spell Reference",
            description: "Raw public spell data from the common package.",
            mimeType: "application/json",
        },
        async (uri) => jsonContents(uri, spellsJson),
    );

    server.registerResource(
        "effect-reference",
        "hoc://effects",
        {
            title: "Heroes of Crypto Effect Reference",
            description: "Raw public effect data from the common package.",
            mimeType: "application/json",
        },
        async (uri) => jsonContents(uri, effectsJson),
    );

    server.registerResource(
        "aura-reference",
        "hoc://auras",
        {
            title: "Heroes of Crypto Aura Reference",
            description: "Raw public aura effect data from the common package.",
            mimeType: "application/json",
        },
        async (uri) => jsonContents(uri, auraEffectsJson),
    );

    server.registerResource(
        "synergy-reference",
        "hoc://synergies",
        {
            title: "Heroes of Crypto Synergy Reference",
            description: "Faction synergy thresholds and powers from the common package.",
            mimeType: "application/json",
        },
        async (uri) => jsonContents(uri, getSynergyReference()),
    );
};
