import { CreatureVals } from "@heroesofcrypto/common";
import { images } from "../generated/image_imports";

// Numeric fallbacks keep the client usable during a rolling common/client deploy (or before a local common
// rebuild refreshes dist). The generated enum is authoritative as soon as the new values are available.
const extendedCreatureVals = CreatureVals as typeof CreatureVals & {
    readonly ARACHNA_QUEEN?: number;
    readonly ARACHNA_SPIDER?: number;
};
const ARACHNA_QUEEN_CREATURE_ID = extendedCreatureVals.ARACHNA_QUEEN ?? 44;
const ARACHNA_SPIDER_CREATURE_ID = extendedCreatureVals.ARACHNA_SPIDER ?? 45;

export const UNIT_ID_TO_IMAGE: Record<number, string> = {
    [CreatureVals.NO_CREATURE]: images.unknown_creature_512,
    [CreatureVals.ORC]: images.orc_512,
    [CreatureVals.SCAVENGER]: images.scavenger_512,
    [CreatureVals.TROGLODYTE]: images.troglodyte_512,
    [CreatureVals.TROLL]: images.troll_512,
    [CreatureVals.MEDUSA]: images.medusa_512,
    [CreatureVals.BEHOLDER]: images.beholder_512,
    [CreatureVals.GOBLIN_KNIGHT]: images.goblin_knight_512,
    [CreatureVals.EFREET]: images.efreet_512,
    [CreatureVals.BLACK_DRAGON]: images.black_dragon_512,
    [CreatureVals.HYDRA]: images.hydra_512,
    [CreatureVals.ABOMINATION]: images.abomination_512,
    [CreatureVals.CENTAUR]: images.centaur_512,
    [CreatureVals.BERSERKER]: images.berserker_512,
    [CreatureVals.WOLF_RIDER]: images.wolf_rider_512,
    [CreatureVals.HARPY]: images.harpy_512,
    [CreatureVals.NOMAD]: images.nomad_512,
    [CreatureVals.HYENA]: images.hyena_512,
    [CreatureVals.CYCLOPS]: images.cyclops_512,
    [CreatureVals.OGRE_MAGE]: images.ogre_mage_512,
    [CreatureVals.THUNDERBIRD]: images.thunderbird_512,
    [CreatureVals.BEHEMOTH]: images.behemoth_512,
    [CreatureVals.FRENZIED_BOAR]: images.frenzied_boar_512,
    [CreatureVals.WOLF]: images.wolf_512,
    [CreatureVals.FAIRY]: images.fairy_512,
    [CreatureVals.LEPRECHAUN]: images.leprechaun_512,
    [CreatureVals.ELF]: images.elf_512,
    [CreatureVals.WHITE_TIGER]: images.white_tiger_512,
    [CreatureVals.SATYR]: images.satyr_512,
    [CreatureVals.MANTIS]: images.mantis_512,
    [CreatureVals.UNICORN]: images.unicorn_512,
    [CreatureVals.GARGANTUAN]: images.gargantuan_512,
    [CreatureVals.PEGASUS]: images.pegasus_512,
    [ARACHNA_QUEEN_CREATURE_ID]: images.arachna_queen_512,
    [ARACHNA_SPIDER_CREATURE_ID]: images.arachna_spider_512,
    [CreatureVals.PEASANT]: images.peasant_512,
    [CreatureVals.SQUIRE]: images.squire_512,
    [CreatureVals.ARBALESTER]: images.arbalester_512,
    [CreatureVals.VALKYRIE]: images.valkyrie_512,
    [CreatureVals.PIKEMAN]: images.pikeman_512,
    [CreatureVals.HEALER]: images.healer_512,
    [CreatureVals.GRIFFIN]: images.griffin_512,
    [CreatureVals.CRUSADER]: images.crusader_512,
    [CreatureVals.TSAR_CANNON]: images.tsar_cannon_512,
    [CreatureVals.ANGEL]: images.angel_512,
    [CreatureVals.CHAMPION]: images.champion_512,
};

export const UNIT_ID_TO_NAME: Readonly<Record<number, string>> = {
    [CreatureVals.NO_CREATURE]: "Unknown",
    [CreatureVals.ORC]: "Orc",
    [CreatureVals.SCAVENGER]: "Scavenger",
    [CreatureVals.TROGLODYTE]: "Troglodyte",
    [CreatureVals.TROLL]: "Troll",
    [CreatureVals.MEDUSA]: "Medusa",
    [CreatureVals.BEHOLDER]: "Beholder",
    [CreatureVals.GOBLIN_KNIGHT]: "Goblin Knight",
    [CreatureVals.EFREET]: "Efreet",
    [CreatureVals.BLACK_DRAGON]: "Black Dragon",
    [CreatureVals.HYDRA]: "Hydra",
    [CreatureVals.ABOMINATION]: "Abomination",
    [CreatureVals.CENTAUR]: "Centaur",
    [CreatureVals.BERSERKER]: "Berserker",
    [CreatureVals.WOLF_RIDER]: "Wolf Rider",
    [CreatureVals.HARPY]: "Harpy",
    [CreatureVals.NOMAD]: "Nomad",
    [CreatureVals.HYENA]: "Hyena",
    [CreatureVals.CYCLOPS]: "Cyclops",
    [CreatureVals.OGRE_MAGE]: "Ogre Mage",
    [CreatureVals.THUNDERBIRD]: "Thunderbird",
    [CreatureVals.BEHEMOTH]: "Behemoth",
    [CreatureVals.FRENZIED_BOAR]: "Frenzied Boar",
    [CreatureVals.WOLF]: "Wolf",
    [CreatureVals.FAIRY]: "Fairy",
    [CreatureVals.LEPRECHAUN]: "Leprechaun",
    [CreatureVals.ELF]: "Elf",
    [CreatureVals.WHITE_TIGER]: "White Tiger",
    [CreatureVals.SATYR]: "Satyr",
    [CreatureVals.MANTIS]: "Mantis",
    [CreatureVals.UNICORN]: "Unicorn",
    [CreatureVals.GARGANTUAN]: "Gargantuan",
    [CreatureVals.PEGASUS]: "Pegasus",
    [ARACHNA_QUEEN_CREATURE_ID]: "Arachna Queen",
    [ARACHNA_SPIDER_CREATURE_ID]: "Arachna Spider",
    [CreatureVals.PEASANT]: "Peasant",
    [CreatureVals.SQUIRE]: "Squire",
    [CreatureVals.ARBALESTER]: "Arbalester",
    [CreatureVals.VALKYRIE]: "Valkyrie",
    [CreatureVals.PIKEMAN]: "Pikeman",
    [CreatureVals.HEALER]: "Healer",
    [CreatureVals.GRIFFIN]: "Griffin",
    [CreatureVals.CRUSADER]: "Crusader",
    [CreatureVals.TSAR_CANNON]: "Tsar Cannon",
    [CreatureVals.ANGEL]: "Angel",
    [CreatureVals.CHAMPION]: "Champion",
};
