import { CreatureVals } from "@heroesofcrypto/common";
import { images } from "../generated/image_imports";

// Numeric fallbacks keep the client usable during a rolling common/client deploy (or before a local common
// rebuild refreshes dist). The generated enum is authoritative as soon as the new values are available.
const extendedCreatureVals = CreatureVals as typeof CreatureVals & {
    readonly ARACHNA_QUEEN?: number;
    readonly ARACHNA_SPIDER?: number;
    readonly MAGIC_DRAGON?: number;
};
const ARACHNA_QUEEN_CREATURE_ID = extendedCreatureVals.ARACHNA_QUEEN ?? 44;
const ARACHNA_SPIDER_CREATURE_ID = extendedCreatureVals.ARACHNA_SPIDER ?? 45;
const MAGIC_DRAGON_CREATURE_ID = extendedCreatureVals.MAGIC_DRAGON ?? 57;

const runtimeImages = images as Readonly<Record<string, string>>;
const pickSandboxPortrait = (slug: string): string => runtimeImages[`${slug}_pick_sandbox_x2`];

export const UNIT_ID_TO_IMAGE: Record<number, string> = {
    [CreatureVals.NO_CREATURE]: images.unknown_creature_512,
    [CreatureVals.ORC]: pickSandboxPortrait("orc"),
    [CreatureVals.SCAVENGER]: pickSandboxPortrait("scavenger"),
    [CreatureVals.TROGLODYTE]: pickSandboxPortrait("troglodyte"),
    [CreatureVals.TROLL]: pickSandboxPortrait("troll"),
    [CreatureVals.MEDUSA]: pickSandboxPortrait("medusa"),
    [CreatureVals.BEHOLDER]: pickSandboxPortrait("beholder"),
    [CreatureVals.GOBLIN_KNIGHT]: pickSandboxPortrait("goblin_knight"),
    [CreatureVals.EFREET]: pickSandboxPortrait("efreet"),
    [CreatureVals.BLACK_DRAGON]: pickSandboxPortrait("black_dragon"),
    [CreatureVals.HYDRA]: pickSandboxPortrait("hydra"),
    [CreatureVals.ABOMINATION]: pickSandboxPortrait("abomination"),
    [CreatureVals.CENTAUR]: pickSandboxPortrait("centaur"),
    [CreatureVals.BERSERKER]: pickSandboxPortrait("berserker"),
    [CreatureVals.WOLF_RIDER]: pickSandboxPortrait("wolf_rider"),
    [CreatureVals.MERMAID]: pickSandboxPortrait("mermaid"),
    [CreatureVals.DRYAD]: pickSandboxPortrait("dryad"),
    [CreatureVals.BLACKSMITH]: pickSandboxPortrait("blacksmith"),
    [CreatureVals.ZENA]: pickSandboxPortrait("zena"),
    [CreatureVals.TRENT]: pickSandboxPortrait("trent"),
    [CreatureVals.WYVERN]: pickSandboxPortrait("wyvern"),
    [CreatureVals.HARPY]: pickSandboxPortrait("harpy"),
    [CreatureVals.NOMAD]: pickSandboxPortrait("nomad"),
    [CreatureVals.HYENA]: pickSandboxPortrait("hyena"),
    [CreatureVals.CYCLOPS]: pickSandboxPortrait("cyclops"),
    [CreatureVals.OGRE_MAGE]: pickSandboxPortrait("ogre_mage"),
    [CreatureVals.THUNDERBIRD]: pickSandboxPortrait("thunderbird"),
    [CreatureVals.BEHEMOTH]: pickSandboxPortrait("behemoth"),
    [CreatureVals.FRENZIED_BOAR]: pickSandboxPortrait("frenzied_boar"),
    [CreatureVals.WOLF]: pickSandboxPortrait("wolf"),
    [CreatureVals.FAIRY]: pickSandboxPortrait("fairy"),
    [CreatureVals.LEPRECHAUN]: pickSandboxPortrait("leprechaun"),
    [CreatureVals.ELF]: pickSandboxPortrait("elf"),
    [CreatureVals.WHITE_TIGER]: pickSandboxPortrait("white_tiger"),
    [CreatureVals.SATYR]: pickSandboxPortrait("satyr"),
    [CreatureVals.MANTIS]: pickSandboxPortrait("mantis"),
    [CreatureVals.UNICORN]: pickSandboxPortrait("unicorn"),
    [CreatureVals.GARGANTUAN]: pickSandboxPortrait("gargantuan"),
    [CreatureVals.PEGASUS]: pickSandboxPortrait("pegasus"),
    [ARACHNA_QUEEN_CREATURE_ID]: pickSandboxPortrait("arachna_queen"),
    [ARACHNA_SPIDER_CREATURE_ID]: pickSandboxPortrait("arachna_spider"),
    [CreatureVals.PEASANT]: pickSandboxPortrait("peasant"),
    [CreatureVals.SQUIRE]: pickSandboxPortrait("squire"),
    [CreatureVals.ARBALESTER]: pickSandboxPortrait("arbalester"),
    [CreatureVals.VALKYRIE]: pickSandboxPortrait("valkyrie"),
    [CreatureVals.PIKEMAN]: pickSandboxPortrait("pikeman"),
    [CreatureVals.HEALER]: pickSandboxPortrait("healer"),
    [CreatureVals.GRIFFIN]: pickSandboxPortrait("griffin"),
    [CreatureVals.CRUSADER]: pickSandboxPortrait("crusader"),
    [CreatureVals.TSAR_CANNON]: pickSandboxPortrait("tsar_cannon"),
    [CreatureVals.ANGEL]: pickSandboxPortrait("angel"),
    [CreatureVals.CHAMPION]: pickSandboxPortrait("champion"),
    [CreatureVals.WANDERING_MAGE]: pickSandboxPortrait("wandering_mage"),
    [CreatureVals.MONK]: pickSandboxPortrait("monk"),
    [CreatureVals.MANTICORE]: pickSandboxPortrait("manticore"),
    [CreatureVals.BATTLE_MAGE]: pickSandboxPortrait("battle_mage"),
    [CreatureVals.NIGHTMARE]: pickSandboxPortrait("nightmare"),
    [MAGIC_DRAGON_CREATURE_ID]: pickSandboxPortrait("magic_dragon"),
};

export const UNIT_ID_TO_NAME: Readonly<Record<number, string>> = {
    [CreatureVals.NO_CREATURE]: "Unknown",
    [CreatureVals.ORC]: "Orc",
    [CreatureVals.SCAVENGER]: "Scavenger",
    [CreatureVals.TROGLODYTE]: "Troglodyte",
    [CreatureVals.TROLL]: "Troll",
    [CreatureVals.MEDUSA]: "Medusa",
    [CreatureVals.BEHOLDER]: "Beholder",
    [CreatureVals.GOBLIN_KNIGHT]: "Goblin Knight",
    [CreatureVals.EFREET]: "Efreet",
    [CreatureVals.BLACK_DRAGON]: "Black Dragon",
    [CreatureVals.HYDRA]: "Hydra",
    [CreatureVals.ABOMINATION]: "Abomination",
    [CreatureVals.CENTAUR]: "Centaur",
    [CreatureVals.BERSERKER]: "Berserker",
    [CreatureVals.WOLF_RIDER]: "Wolf Rider",
    [CreatureVals.MERMAID]: "Mermaid",
    [CreatureVals.DRYAD]: "Dryad",
    [CreatureVals.BLACKSMITH]: "Blacksmith",
    [CreatureVals.ZENA]: "Zena",
    [CreatureVals.TRENT]: "Trent",
    [CreatureVals.WYVERN]: "Wyvern",
    [CreatureVals.HARPY]: "Harpy",
    [CreatureVals.NOMAD]: "Nomad",
    [CreatureVals.HYENA]: "Hyena",
    [CreatureVals.CYCLOPS]: "Cyclops",
    [CreatureVals.OGRE_MAGE]: "Ogre Mage",
    [CreatureVals.THUNDERBIRD]: "Thunderbird",
    [CreatureVals.BEHEMOTH]: "Behemoth",
    [CreatureVals.FRENZIED_BOAR]: "Frenzied Boar",
    [CreatureVals.WOLF]: "Wolf",
    [CreatureVals.FAIRY]: "Fairy",
    [CreatureVals.LEPRECHAUN]: "Leprechaun",
    [CreatureVals.ELF]: "Elf",
    [CreatureVals.WHITE_TIGER]: "White Tiger",
    [CreatureVals.SATYR]: "Satyr",
    [CreatureVals.MANTIS]: "Mantis",
    [CreatureVals.UNICORN]: "Unicorn",
    [CreatureVals.GARGANTUAN]: "Gargantuan",
    [CreatureVals.PEGASUS]: "Pegasus",
    [ARACHNA_QUEEN_CREATURE_ID]: "Arachna Queen",
    [ARACHNA_SPIDER_CREATURE_ID]: "Arachna Spider",
    [CreatureVals.PEASANT]: "Peasant",
    [CreatureVals.SQUIRE]: "Squire",
    [CreatureVals.ARBALESTER]: "Arbalester",
    [CreatureVals.VALKYRIE]: "Valkyrie",
    [CreatureVals.PIKEMAN]: "Pikeman",
    [CreatureVals.HEALER]: "Healer",
    [CreatureVals.GRIFFIN]: "Griffin",
    [CreatureVals.CRUSADER]: "Crusader",
    [CreatureVals.TSAR_CANNON]: "Tsar Cannon",
    [CreatureVals.ANGEL]: "Angel",
    [CreatureVals.CHAMPION]: "Champion",
    [CreatureVals.WANDERING_MAGE]: "Wandering Mage",
    [CreatureVals.MONK]: "Monk",
    [CreatureVals.MANTICORE]: "Manticore",
    [CreatureVals.BATTLE_MAGE]: "Battle Mage",
    [CreatureVals.NIGHTMARE]: "Nightmare",
    [MAGIC_DRAGON_CREATURE_ID]: "Magic Dragon",
};

/** Reverse lookup for UI payloads that still carry a creature name instead of its numeric id. */
export const UNIT_NAME_TO_ID: Readonly<Record<string, number>> = Object.freeze(
    Object.fromEntries(Object.entries(UNIT_ID_TO_NAME).map(([creatureId, name]) => [name, Number(creatureId)])),
);

export const fullBodyCreatureImage = (creatureId: number): string | undefined => UNIT_ID_TO_IMAGE[creatureId];
