// scripts/generate_image_imports.js
const fs = require("fs");
const path = require("path");

const imageDir = path.resolve(__dirname, "../images");
const generatedDir = path.resolve(__dirname, "../src/generated");
const outputFile = path.join(generatedDir, "image_imports.ts");

const SEGMENT_NAME_TO_IMPORT_NAME = {
    0: "zero",
    1: "one",
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
};
// stop.webp is intentionally registered (key "stop") — the on-unit / Alt-view / UpNext "stopped" (skip)
// badge shown for Stun / Blindness / Freeze, replacing the old stun_256 corner icon.
const EXCLUDED_IMAGE_FILES = new Set([]);

if (!fs.existsSync(generatedDir)) fs.mkdirSync(generatedDir, { recursive: true });

const files = fs.readdirSync(imageDir);
const entries = [];

for (const file of files) {
    if (
        file.endsWith(".webp") &&
        !EXCLUDED_IMAGE_FILES.has(file) &&
        !file.startsWith("synergy_") &&
        !file.startsWith("overlay_") &&
        !file.startsWith("icon_")
    ) {
        const segs = file.split("_");
        if (!segs.length) continue;
        const first = segs[0];
        const base = `${SEGMENT_NAME_TO_IMPORT_NAME[first] || first}_${segs.slice(1).join("_")}`;
        let cutBy = 5;
        if (base.endsWith("_")) cutBy = 6;
        const key = base.substring(0, base.length - cutBy);
        entries.push({ key, file });
    }
}

const lines = [];
lines.push("/* AUTO-GENERATED BY scripts/generate_image_imports.js — DO NOT EDIT */");
lines.push("/* eslint-disable */");
lines.push("");
lines.push("export const images = {");
for (const { key, file } of entries) {
    // IMPORTANT: path is relative to THIS .ts file location (src/generated)
    lines.push(`  "${key}": new URL("../../images/${file}", import.meta.url).toString(),`);
}
lines.push("} as const;");
lines.push("");
lines.push("export type ImageKey = keyof typeof images;");

fs.writeFileSync(outputFile, lines.join("\n") + "\n");
console.log("Image imports generated successfully.");
