// scripts/generate_image_imports.js
const fs = require("fs");
const path = require("path");
const { isWebPFile } = require("../src/gameImageAssetPolicy.ts");

const imageDir = path.resolve(__dirname, "../images");
const generatedDir = path.resolve(__dirname, "../src/generated");
const outputFile = path.join(generatedDir, "image_imports.ts");
const productionBuild = process.env.NODE_ENV === "production";
const { isProductionOmittedAssetKey } = require("../src/pixi/imageAssetTiers.ts");

const SEGMENT_NAME_TO_IMPORT_NAME = {
    0: "zero",
    1: "one",
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
};
// stop.webp is intentionally registered (key "stop") — the on-unit / Alt-view / UpNext "stopped" (skip)
// badge shown for Stun / Blindness / Freeze, replacing the old stun_256 corner icon.
const EXCLUDED_IMAGE_FILES = new Set([
    "dungeon_volumetric_fog_v1.webp",
    "dungeon_god_rays_v1.webp",
    "background_stone_tiles_sinister_16x16_brown.webp",
    "background_stone_tiles_lava.webp",
]);
if (!fs.existsSync(generatedDir)) fs.mkdirSync(generatedDir, { recursive: true });

const files = fs.readdirSync(imageDir);
const entries = [];

for (const file of files) {
    const extension = path.extname(file).toLowerCase();
    if (
        isWebPFile(file) &&
        !EXCLUDED_IMAGE_FILES.has(file) &&
        !file.startsWith("synergy_") &&
        !file.startsWith("overlay_") &&
        !file.startsWith("icon_")
    ) {
        const segs = path.basename(file, extension).split("_");
        if (!segs.length) continue;
        const first = segs.shift();
        if (!first) continue;
        const key = [SEGMENT_NAME_TO_IMPORT_NAME[first] || first, ...segs].join("_");
        entries.push({ key, file, productionOmitted: productionBuild && isProductionOmittedAssetKey(key) });
    }
}

const lines = [];
lines.push("/* AUTO-GENERATED BY scripts/generate_image_imports.js — DO NOT EDIT */");
lines.push("/* eslint-disable */");
lines.push("");
lines.push("export const images = {");
for (const { key, file, productionOmitted } of entries) {
    // IMPORTANT: path is relative to THIS .ts file location (src/generated)
    lines.push(
        productionOmitted
            ? `  "${key}": undefined as unknown as string,`
            : `  "${key}": new URL("../../images/${file}", import.meta.url).toString(),`,
    );
}
lines.push("} as const;");
lines.push("");
lines.push("export type ImageKey = keyof typeof images;");

fs.writeFileSync(outputFile, lines.join("\n") + "\n");
const omittedCount = entries.filter(({ productionOmitted }) => productionOmitted).length;
console.log(
    productionBuild
        ? `Image imports generated successfully (${omittedCount} authoring/legacy assets omitted from production).`
        : "Image imports generated successfully.",
);
