// scripts/generate_image_imports.js
const fs = require("fs");
const path = require("path");
const { isWebPFile } = require("../src/gameImageAssetPolicy.ts");

const imageDir = path.resolve(__dirname, "../images");
const generatedDir = path.resolve(__dirname, "../src/generated");
const outputFile = path.join(generatedDir, "image_imports.ts");

const SEGMENT_NAME_TO_IMPORT_NAME = {
    0: "zero",
    1: "one",
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
};
// stop.webp is intentionally registered (key "stop") — the on-unit / Alt-view / UpNext "stopped" (skip)
// badge shown for Stun / Blindness / Freeze, replacing the old stun_256 corner icon.
const EXCLUDED_IMAGE_FILES = new Set([
    "dungeon_volumetric_fog_v1.webp",
    "dungeon_god_rays_v1.webp",
    "background_stone_tiles_sinister_16x16_brown.webp",
    "background_stone_tiles_lava.webp",
]);
const SUPPORTED_IMAGE_EXTENSIONS = new Set([".webp", ".png", ".jpg", ".jpeg", ".gif", ".avif"]);
// The Dropbox-backed copies of these cursors may be online-only placeholders (0-byte files).
// Keep cursors in Vite's public directory so local startup never depends on Dropbox hydration.
const PUBLIC_CURSOR_PATHS = new Map([
    ["cursor_default.webp", "/cursors/cursor_default.png"],
    ["cursor_interactive.webp", "/cursors/cursor_interactive.png"],
    ["cursor_magic.webp", "/cursors/cursor_magic.png"],
    ["cursor_melee.webp", "/cursors/cursor_melee.png"],
    ["cursor_ranged.webp", "/cursors/cursor_ranged.png"],
]);
const PUBLIC_STATIC_IMAGES = new Map([
    ["deployment_grid_glow_master_16x6", "/textures/deployment_grid_glow_master_16x6.png?v=1"],
    ["spell_cast_scroll_variant2", "/spellbook/spell_cast_scroll_variant2.png?v=2"],
    ["spell_stack_fill_green_variant2", "/spellbook/spell_stack_fill_green_variant2.png?v=2"],
    ["spell_stack_fill_red_variant2", "/spellbook/spell_stack_fill_red_variant2.png?v=2"],
    ["spell_stack_rail_variant2", "/spellbook/spell_stack_rail_variant2.png?v=2"],
]);

if (!fs.existsSync(generatedDir)) fs.mkdirSync(generatedDir, { recursive: true });

const files = fs.readdirSync(imageDir);
const entries = [];

for (const file of files) {
    const extension = path.extname(file).toLowerCase();
    const isEmptyDropboxPlaceholder =
        fs.statSync(path.join(imageDir, file)).size === 0 && !PUBLIC_CURSOR_PATHS.has(file);
    if (
        SUPPORTED_IMAGE_EXTENSIONS.has(extension) &&
        !isEmptyDropboxPlaceholder &&
        !EXCLUDED_IMAGE_FILES.has(file) &&
        !file.startsWith("synergy_") &&
        !file.startsWith("overlay_") &&
        !file.startsWith("icon_")
    ) {
        const segs = path.basename(file, extension).split("_");
        if (!segs.length) continue;
        const first = segs.shift();
        if (!first) continue;
        const key = [SEGMENT_NAME_TO_IMPORT_NAME[first] || first, ...segs].join("_");
        if (PUBLIC_STATIC_IMAGES.has(key)) continue;
        entries.push({ key, file });
    }
}

const lines = [];
lines.push("/* AUTO-GENERATED BY scripts/generate_image_imports.js — DO NOT EDIT */");
lines.push("/* eslint-disable */");
lines.push("");
lines.push("export const images = {");
for (const [key, publicPath] of PUBLIC_STATIC_IMAGES) {
    lines.push(`  "${key}": "${publicPath}",`);
}
for (const { key, file } of entries) {
    const publicCursorPath = PUBLIC_CURSOR_PATHS.get(file);
    if (publicCursorPath) {
        lines.push(`  "${key}": "${publicCursorPath}",`);
        continue;
    }
    // IMPORTANT: path is relative to THIS .ts file location (src/generated)
    lines.push(`  "${key}": new URL("../../images/${file}", import.meta.url).toString(),`);
}
lines.push("} as const;");
lines.push("");
lines.push("export type ImageKey = keyof typeof images;");

fs.writeFileSync(outputFile, lines.join("\n") + "\n");
console.log("Image imports generated successfully.");
