// scripts/generate_animation_atlases.js
/* eslint-disable no-console */
const fs = require("fs");
const path = require("path");

// Root directory where all meta.jsons live (you can override via CLI)
const animationsRoot =
    process.argv[2] || (process.env.HOC_ANIMATIONS_LOC ? path.join(process.env.HOC_ANIMATIONS_LOC, "output") : null);

if (!animationsRoot) {
    console.error("Animations root not specified. Provide a path as the first CLI argument or set HOC_ANIMATIONS_LOC.");
    process.exit(1);
}

// TARGET IMAGES DIR: ../images from this script location
const imagesDir = path.resolve(__dirname, "../images");

const generatedDir = path.resolve(__dirname, "../src/generated");
const outputFile = path.join(generatedDir, "animation_atlases.ts");

// Ensure generated + images dirs exist
if (!fs.existsSync(generatedDir)) {
    fs.mkdirSync(generatedDir, { recursive: true });
}
if (!fs.existsSync(imagesDir)) {
    fs.mkdirSync(imagesDir, { recursive: true });
}

function walkDir(dir, acc = []) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            walkDir(full, acc);
        } else {
            acc.push(full);
        }
    }
    return acc;
}

// Turn "wolf_rider" -> "Wolf Rider", "angel" -> "Angel"
function toUnitName(base) {
    return base
        .split("_")
        .filter(Boolean)
        .map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1))
        .join(" ");
}

// Extract { unitName, state } from "angel_default_meta.json" / "wolf_rider_default_meta.json"
function parseMetaFileName(filePath) {
    const fileName = path.basename(filePath, ".json"); // e.g. "angel_default_meta"
    const withoutMeta = fileName.replace(/_meta$/, ""); // "angel_default"
    const parts = withoutMeta.split("_");
    if (parts.length < 2) {
        return null;
    }
    const state = parts[parts.length - 1]; // "default"
    const base = parts.slice(0, -1).join("_"); // "angel", "wolf_rider"
    const unitName = toUnitName(base); // "Angel", "Wolf Rider"
    return { unitName, state };
}

function main() {
    const root = path.resolve(animationsRoot);

    if (!fs.existsSync(root)) {
        console.warn(`Animations root does not exist: ${root}`);
        process.exit(0);
    }

    console.log(`Scanning for *_meta.json and *_atlas.webp under: ${root}`);
    console.log(`Atlas .webp files will be copied into: ${imagesDir}`);

    const allFiles = walkDir(root, []);

    const metaFiles = allFiles.filter((f) => f.endsWith("_meta.json")).sort();
    const atlasWebps = allFiles
        .filter(
            (f) =>
                f.endsWith(".webp") &&
                f.includes(`${path.sep}atlas${path.sep}`) &&
                (f.endsWith("_atlas.webp") || f.endsWith("_atlas_quarter.webp") || f.endsWith("_atlas_half.webp")),
        )
        .sort();

    if (metaFiles.length === 0) {
        console.error("No *_meta.json files found.");
        process.exit(1);
    }

    /** @type {Record<string, Record<string, any>>} */
    const atlasMap = {};

    // --- Build TS meta map ---------------------------------------------------
    for (const file of metaFiles) {
        const info = parseMetaFileName(file);
        if (!info) {
            console.warn(`Skipping (cannot parse name): ${file}`);
            continue;
        }

        const { unitName, state } = info;

        const raw = fs.readFileSync(file, "utf8");
        let json;
        try {
            json = JSON.parse(raw);
        } catch (err) {
            console.warn(`Skipping (invalid JSON): ${file}`, err);
            continue;
        }

        if (!json.meta) {
            console.warn(`Skipping (no "meta" field): ${file}`);
            continue;
        }

        const meta = json.meta;

        // ⭐️ Derive animation timings from totalDurationSec
        if (typeof meta.totalDurationSec === "number" && Number.isFinite(meta.totalDurationSec)) {
            const baseTotalMs = meta.totalDurationSec * 1000;
            const loopDurationMs = Math.round(baseTotalMs * 0.9); // 10% faster
            const pauseMs = Math.round(loopDurationMs * 0.4); // 40% of loopDurationMs

            meta.loopDurationMs = loopDurationMs;
            meta.pauseMs = pauseMs;
        }

        if (!atlasMap[unitName]) {
            atlasMap[unitName] = {};
        }
        atlasMap[unitName][state] = meta;
    }

    const lines = [];
    lines.push("/* AUTO-GENERATED BY scripts/generate_animation_atlases.js — DO NOT EDIT */");
    lines.push("/* eslint-disable */");
    lines.push("");
    lines.push("/**");
    lines.push(" * One atlas entry per unit per animation state. Typed as an EXPLICIT record on purpose:");
    lines.push(" * the old `as const` + distributed-keyof types collapsed every indexed lookup to `never`");
    lines.push(' * the moment the external art set went heterogeneous (a unit shipping only an "attack"');
    lines.push(' * atlas while the rest carry "default"), which broke the client build at deploy time');
    lines.push(" * even though CI — with no external art drive — stayed green. Consumers already resolve units and");
    lines.push(" * states at runtime (`name in animationAtlases`, `Object.keys(...)`), so string keys");
    lines.push(" * with a strict value shape is the honest contract.");
    lines.push(" */");
    lines.push("export interface IAtlasAnimationMeta {");
    lines.push("    frameWidth: number;");
    lines.push("    frameHeight: number;");
    lines.push("    atlasWidth: number;");
    lines.push("    atlasHeight: number;");
    lines.push("    frameCount: number;");
    lines.push("    fps: number;");
    lines.push("    frameDurationSec: number;");
    lines.push("    totalDurationSec: number;");
    lines.push("    layout: { cols: number; rows: number };");
    lines.push("    footAnchorY?: number;");
    lines.push("    loopDurationMs: number;");
    lines.push("    pauseMs: number;");
    lines.push("    /** Forward-compat: Google Drive art metadata evolves ahead of this generator (e.g. the");
    lines.push("     * multi-phase intro/walk animation data). Undeclared keys pass through untyped so a");
    lines.push("     * new meta field never breaks the DEPLOY build while CI (no external art drive) stays green. */");
    lines.push("    [key: string]: unknown;");
    lines.push("}");
    lines.push("");
    lines.push(
        "export const animationAtlases: Readonly<Record<string, Readonly<Record<string, IAtlasAnimationMeta>>>> =",
    );
    lines.push(JSON.stringify(atlasMap, null, 2) + ";");
    lines.push("");
    lines.push("export type AnimationUnitName = string;");
    lines.push("export type AnimationStateName<_U extends AnimationUnitName = AnimationUnitName> = string;");
    lines.push("");

    fs.writeFileSync(outputFile, lines.join("\n"), "utf8");
    console.log(`✅ Animation atlas meta generated successfully: ${outputFile}`);

    // --- Copy atlas .webp files into ../images ------------------------------
    let copied = 0;
    for (const file of atlasWebps) {
        const dest = path.join(imagesDir, path.basename(file));
        try {
            fs.copyFileSync(file, dest);
            copied++;
        } catch (err) {
            console.warn(`Failed to copy atlas webp: ${file} -> ${dest}`, err);
        }
    }

    console.log(`✅ Copied ${copied} atlas .webp files into: ${imagesDir}`);
}

main();
